### ISSUE TITLE
db_clean.sql

### ISSUE THREAD

**Issue by Stiyx** [Kev5454/litotex#6]
Encounter Troubleshoot while installing, lies on 
`_crand`

same occurs at `_pages`
primary key double defined.
[db_clean-sql.txt](https://github.com/Kev5454/litotex/files/1564832/db_clean-sql.txt)

fixed within this file.

**Comment by Kev5454** [comment]
CREATE TABLE `cc{#SERVERID#}_pages` (
  `id` int(12) UNSIGNED NOT NULL,
  `getName` varchar(128) NOT NULL,
  `title` varchar(255) NOT NULL,
  `content` text NOT NULL,
  `access` enum('public','member','support','admin') NOT NULL,
  `isActive` tinyint(2) UNSIGNED NOT NULL,
  `makeTime` int(12) UNSIGNED NOT NULL,
  `updateTime` int(12) UNSIGNED NOT NULL,
  PRIMARY KEY  (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `cc{#SERVERID#}_crand` (
  `crand_id` int(11) NOT NULL auto_increment,
  `x` int(5) NOT NULL,
  `y` int(5) NOT NULL,
  `used` tinyint(1) NOT NULL default '0',
  `element_type` int(2) NOT NULL default '0' ,
   PRIMARY KEY  (`crand_id`)
);

Primary Keys has not double defined... Please, Errorlog or Stacktrace .

Lg,
K. Wehmeyer

**Comment by noaim90** [comment]
I still get this too at step 3
Fehler:Beim importieren ist ein Fehler aufgetreten
CREATE TABLE IF NOT EXISTS `cc1_crand` ( `crand_id` int(11) NOT NULL auto_increment, `x` int(5) NOT NULL, `y` int(5) NOT NULL, `used` tinyint(1) NOT NULL default '0', `element_type` int(2) NOT NULL default '0' );

**Comment by Kev5454** [comment]
Danke, fehler wurde behoben!
