### ISSUE TITLE
Projekt noch aktuell ? - Link führt auf eine Einrichtungsseite

### ISSUE THREAD

**Issue by agony09** [Kev5454/litotex#8]
Wollte mal fragen, ob dieses Projekt noch aktuell ist ?
Denn der Link der hier angegeben wird führt zu einer Einrichtungsseite.

**Comment by agony09** [comment]
Na dann sage ich doch mal Danke für die Antwort....

**Comment by Kev5454** [comment]
Die Webseite habe ich offline genommen da diese nicht benutzt wurde ausschließlich werde ich alles über Github machen.  

Tut mir leid.
